version: '3'
services:
  mysql_db:
    image: mysql # docker pull mysql
    container_name: mysql_db
    ports:
      - 3306:3306
    networks:
      - node-work-2
    environment:
      - MYSQL_ROOT_PASSWORD=1234

  node-be:
    depends_on:
      - mysql_db
    build: . # docker build . -t img-node
    container_name: node-be
    ports:
      - 8080:8080
    networks:
      - node-work-2

  react-fe:
    build: ./node41_frontend

volumes:
  mysql_db:
    driver: local

networks:
  node-work-2:

# docker-compose up -d
# docker-compose down